### PR TITLE
Updated to 1.20.1 to match with Fabric Generator

### PR DESCRIPTION
**Pull request by PSGitHubUser1**
I have made changes in these types of files for first time. I know that my 2 hours will be wasted as Nerdy will find that this PR is wrong or trash. I just wanted to help. I am not even sure that the PortingLib API is even got updated for 1.20.1 or not I did that from this [mod](https://www.curseforge.com/minecraft/mc-mods/porting-lib), as this plugin is get updates from [here](https://github.com/Fabricators-of-Create/Porting-Lib). Nerdy if I did something wrong please do not close this PR instantly (please), let me know if I could be able to fix it? 

```disappointment.md
I know that I wasted my whole 2 hours for no reason. No worries, if you reject this then there will be a issue. ;( 
```

### CODE REVIEW

**Comment by PSGitHubUser1** [comment]
I have invited you to my repo. [Fork of this Repo].

Just incase, if you want to do something.

**Comment by NerdyPuzzle** [comment]
Are you kidding me? All you did was copy everything from 1.19.2, and you didn't even include the fabric essentials API for 1.20.1... If you're going to open a pull request, at least try to test it...

**Comment by PSGitHubUser1** [comment]
That is what I was thinking, I do not even know where is the PortingLib API for 1.20.1 is...
That is why I included the mod from Curseforge, not from the FoC/Porting-Lib (GitHub) as I saw that the latest branch is upto 1.19.4 and I was doing for the 1.20.1

Sorry if I have wasted your time for reviewing as I already said that This is my first time editing this type of files.

**Comment by PSGitHubUser1** [comment]
Affernative.

**Pull request closed without merging**
